### ISSUE TITLE
s/gen triggers IllegalArgumentException for nested aliased specs

### ISSUE THREAD

**Issue by johanwiren** [metosin/spec-tools#94]
Environment:
clojure 1.9.0
spec-tools 0.5.1 (also re-created on 0.6.0-SNAPSHOT)

With these specs:
```clojure
(s/def ::string string?)
(s/def ::alias ::string)
(s/def ::nested-alias (st/spec ::alias))
```

When calling
```clojure
(s/gen ::nested-alias)
```

An *IllegalArgumentException* is thrown
Stack trace:
```java
Caused by: java.lang.IllegalArgumentException: No implementation of method: :gen* of protocol: #'clojure.spec.alpha/Spec found for class: clojure.lang.Keyword
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at clojure.spec.alpha$fn__1666$G__1614__1677.invoke(alpha.clj:37)
	at spec_tools.core.Spec.gen_STAR_(core.cljc:202)
	at clojure.spec.alpha$gensub.invokeStatic(alpha.clj:266)
	at clojure.spec.alpha$gensub.invoke(alpha.clj:259)
	at clojure.spec.alpha$map_spec_impl$reify__1931$gen__1972.invoke(alpha.clj:834)
	at clojure.core$map$fn__5591.invoke(core.clj:2752)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$concat$fn__5215.invoke(core.clj:717)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.LazySeq.next(LazySeq.java:81)
	at clojure.lang.RT.next(RT.java:706)
	at clojure.core$next__5108.invokeStatic(core.clj:64)
	at clojure.core$every_QMARK_.invokeStatic(core.clj:2673)
	at clojure.core$every_QMARK_.invoke(core.clj:2664)
	at clojure.spec.alpha$map_spec_impl$reify__1931.gen_STAR_(alpha.clj:840)
	at spec_tools.core.Spec.gen_STAR_(core.cljc:202)
	at clojure.spec.alpha$gensub.invokeStatic(alpha.clj:266)
	at clojure.spec.alpha$gensub.invoke(alpha.clj:259)
	at clojure.spec.alpha$gen.invokeStatic(alpha.clj:283)
	at clojure.spec.alpha$gen.invoke(alpha.clj:272)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
	... 72 more
```

**Comment by ikitommi** [comment]
deployed in `[metosin/spec-tools "0.6.0-20171221.064855-2"]`
